server:
  port: 8080
spring:
  application:
    name: spring-security-registerlogin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  sql:
    init:
      schema-locations: classpath:db/mysql/schema.sql
      data-locations: classpath:db/mysql/data.sql
      mode: always
      continue-on-error: true
